[package]
name = "dir-lock"
version = "0.3.1"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"
description = "A simple file-system-based mutex"
license = "MIT"
readme = "README.md"
repository = "https://github.com/fenhl/rust-dir-lock"

[features]
default = ["tokio"]

[patch.crates-io.darwin-libproc] # see https://github.com/heim-rs/darwin-libproc/pull/3 for details
git = "https://github.com/Orycterope/darwin-libproc"
branch = "dependencies_versions"

[dependencies]
thiserror = "1"

[dependencies.async-std]
version = "1"
optional = true

[dependencies.heim] # see https://github.com/heim-rs/heim/issues/322 for details
git = "https://github.com/fenhl/heim"
branch = "compile-fix"
features = ["process"]

[dependencies.tokio]
version = "1"
optional = true
features = ["fs", "io-util", "rt-multi-thread", "time"]

[dependencies.tokio02]
package = "tokio"
version = "0.2"
optional = true
features = ["fs", "rt-threaded", "time"]

[dependencies.tokio03]
package = "tokio"
version = "0.3"
optional = true
features = ["fs", "io-util", "rt-multi-thread", "time"]
