[package]
name = "dir-lock"
version = "0.3.0"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"
description = "A simple file-system-based mutex"
license = "MIT"
readme = "README.md"
repository = "https://github.com/fenhl/rust-dir-lock"

[features]
default = ["tokio"]

[dependencies]
derive_more = "0.99"
heim = "0.0.11"

[dependencies.async-std]
version = "1"
optional = true

[dependencies.tokio]
version = "1"
optional = true
features = ["fs", "io-util", "rt-multi-thread", "time"]

[dependencies.tokio02]
package = "tokio"
version = "0.2"
optional = true
features = ["fs", "rt-threaded", "time"]

[dependencies.tokio03]
package = "tokio"
version = "0.3"
optional = true
features = ["fs", "io-util", "rt-multi-thread", "time"]
