[package]
name = "dir-lock"
version = "0.1.0"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"
description = "A simple file-system-based mutex"
license = "MIT"
readme = "README.md"
repository = "https://github.com/fenhl/rust-dir-lock"

[dependencies]
async-std = "1"
derive_more = "0.99"
heim = "0.0.10"
